"use client"

import { useState, useEffect } from "react"
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "../components/ui/card"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "../components/ui/tabs"
import { Button } from "../components/ui/button"
import { Loader2, BookOpen, MessageSquare, Download, Printer } from "lucide-react"
import { Badge } from "../components/ui/badge"

interface TrainingRecommendationsProps {
  userId: string
  userName: string
  dominantType: string
}

interface RecommendationsData {
  trainingRecommendations: string[]
  communicationTips: string[]
}

export function TrainingRecommendations({ userId, userName, dominantType }: TrainingRecommendationsProps) {
  const [data, setData] = useState<RecommendationsData | null>(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)

  // Get the color based on DISC type
  const getTypeColor = (type: string) => {
    switch (type) {
      case "D":
        return "bg-red-100 text-red-800 border-red-300"
      case "I":
        return "bg-yellow-100 text-yellow-800 border-yellow-300"
      case "S":
        return "bg-green-100 text-green-800 border-green-300"
      case "C":
        return "bg-blue-100 text-blue-800 border-blue-300"
      default:
        return "bg-gray-100 text-gray-800 border-gray-300"
    }
  }

  useEffect(() => {
    const fetchRecommendations = async () => {
      try {
        setLoading(true)
        const response = await fetch(`/api/training/${userId}`)

        if (!response.ok) {
          throw new Error("Failed to fetch recommendations")
        }

        const data = await response.json()
        setData(data)
      } catch (err) {
        setError("Failed to load recommendations. Please try again later.")
        console.error("Error fetching recommendations:", err)
      } finally {
        setLoading(false)
      }
    }

    fetchRecommendations()
  }, [userId])

  const handlePrint = () => {
    window.print()
  }

  const handleDownload = () => {
    if (!data) return

    const content = `
# Personalized Development Plan for ${userName}
## Dominant Personality Type: ${dominantType}

## Training Recommendations
${data.trainingRecommendations.map((rec, i) => `${i + 1}. ${rec}`).join("\n\n")}

## Communication Strategies
${data.communicationTips.map((tip, i) => `${i + 1}. ${tip}`).join("\n\n")}

Generated by Tafsula - ${new Date().toLocaleDateString()}
    `

    const blob = new Blob([content], { type: "text/plain" })
    const url = URL.createObjectURL(blob)
    const a = document.createElement("a")
    a.href = url
    a.download = `${userName.replace(/\s+/g, "-").toLowerCase()}-development-plan.txt`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }

  if (loading) {
    return (
      <Card className="w-full">
        <CardContent className="pt-6 flex flex-col items-center justify-center min-h-[300px]">
          <Loader2 className="h-8 w-8 animate-spin text-primary mb-4" />
          <p className="text-muted-foreground">Generating personalized recommendations...</p>
        </CardContent>
      </Card>
    )
  }

  if (error) {
    return (
      <Card className="w-full">
        <CardContent className="pt-6">
          <div className="text-center text-red-500">
            <p>{error}</p>
            <Button variant="outline" className="mt-4" onClick={() => window.location.reload()}>
              Try Again
            </Button>
          </div>
        </CardContent>
      </Card>
    )
  }

  return (
    <Card className="w-full">
      <CardHeader>
        <div className="flex items-center justify-between">
          <div>
            <CardTitle className="text-2xl">Personalized Development Plan</CardTitle>
            <CardDescription>AI-generated recommendations based on DISC assessment results</CardDescription>
          </div>
          <Badge className={`text-sm py-1 px-3 ${getTypeColor(dominantType)}`}>Type {dominantType}</Badge>
        </div>
      </CardHeader>
      <CardContent>
        <Tabs defaultValue="training" className="w-full">
          <TabsList className="grid w-full grid-cols-2">
            <TabsTrigger value="training" className="flex items-center gap-2">
              <BookOpen className="h-4 w-4" />
              <span>Training Recommendations</span>
            </TabsTrigger>
            <TabsTrigger value="communication" className="flex items-center gap-2">
              <MessageSquare className="h-4 w-4" />
              <span>Communication Strategies</span>
            </TabsTrigger>
          </TabsList>
          <TabsContent value="training" className="mt-4 space-y-4">
            {data?.trainingRecommendations.map((recommendation, index) => (
              <div key={index} className="p-4 border rounded-lg bg-card">
                <p className="whitespace-pre-line">{recommendation}</p>
              </div>
            ))}
          </TabsContent>
          <TabsContent value="communication" className="mt-4 space-y-4">
            {data?.communicationTips.map((tip, index) => (
              <div key={index} className="p-4 border rounded-lg bg-card">
                <p className="whitespace-pre-line">{tip}</p>
              </div>
            ))}
          </TabsContent>
        </Tabs>
      </CardContent>
      <CardFooter className="flex justify-end gap-2 border-t pt-4">
        <Button variant="outline" onClick={handlePrint} className="flex items-center gap-2">
          <Printer className="h-4 w-4" />
          <span>Print</span>
        </Button>
        <Button onClick={handleDownload} className="flex items-center gap-2">
          <Download className="h-4 w-4" />
          <span>Download Plan</span>
        </Button>
      </CardFooter>
    </Card>
  )
}
